# Modified from https://blob.build/docs/upload/github-action/
name: Publish build

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Upload build
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3.4.1
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn clean package

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: Wildernether
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}